codecov:
  require_ci_to_pass: yes
  notify:
    after_n_builds: 30
    wait_for_ci: yes

coverage:
  status:
    project:
      default:
        # Basic settings
        target: auto
        threshold: 1%
        if_ci_failed: success
        base: auto
        branches:
          - main
    patch:
      default:
        # Settings for new code in PRs
        target: auto
        threshold: 1%
        if_ci_failed: success
        base: auto

# Configure codecov bot behavior
comment:
  # Only post comment after all builds finish
  after_n_builds: 15
  # Hide PR comment if there are no changes
  require_changes: true
  # Add a summary header
  layout: "condensed_header, condensed_files, condensed_footer"
  hide_project_coverage: true

# Ignore certain paths/files
ignore:
  - "test/**/*"
  - "website/**/*"

github_checks:
  annotations: false
